# Generated by Django 4.2.11 on 2026-07-21 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_registration_fee_registration_amount_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='certificate_template',
            field=models.ImageField(blank=True, null=True, upload_to='certificate_templates/'),
        ),
    ]
