# Generated by Django 4.2.11 on 2026-07-26 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_certificate_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='payment_scanner',
            field=models.ImageField(blank=True, null=True, upload_to='payment_scanners/'),
        ),
        migrations.AddField(
            model_name='registration',
            name='payment_screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='payment_screenshots/'),
        ),
    ]
