# Generated by Django 4.2.11 on 2026-07-26 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_payment_scanner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='skills_learned',
            field=models.CharField(blank=True, help_text='Comma-separated list of skills learned e.g. Python, AI, Leadership', max_length=300, null=True),
        ),
    ]
